language: go

sudo: false

go:
- 1.5.3
- 1.6.3
- 1.7
- tip

env:
- GO15VENDOREXPERIMENT=1

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get -t .

matrix:
  allow_failures:
  - go: tip

script:
- make build
- make test
- make cover
- goveralls -service=travis-ci -v -covermode=count -coverprofile=profile.out
