version: 2.1

orbs:
  moul: moul/build@1.12.1 # https://github.com/moul/build

workflows:
  main:
    jobs:
      - moul/golang-build:
          gopkg: moul.io/number-to-words
      - moul/docker-build
